name: resnet-training

resources:
  accelerators: RTX4060-SHARED:1
  cpus: 2
  memory: 4+

setup: |
  pip install torch torchvision

run: |
  echo "Starting training on RTX 4060..."
  python3 -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'Device: {torch.cuda.get_device_name(0)}')"
  
  # Download and train a simple ResNet (using a script created inline just for demo)
  cat <<EOF > train_resnet.py
  import torch
  import torch.nn as nn
  import torch.optim as optim
  import torchvision
  import torchvision.transforms as transforms
  
  def main():
      device = 'cuda' if torch.cuda.is_available() else 'cpu'
      print(f'Using device: {device}')
      
      transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
      trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
      trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle=True, num_workers=2)
      
      net = torchvision.models.resnet18(num_classes=10).to(device)
      criterion = nn.CrossEntropyLoss()
      optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
      
      print('Starting training loop...')
      for epoch in range(1):  # Just 1 epoch for smoke test
          running_loss = 0.0
          for i, data in enumerate(trainloader, 0):
              inputs, labels = data
              inputs, labels = inputs.to(device), labels.to(device)
              
              optimizer.zero_grad()
              outputs = net(inputs)
              loss = criterion(outputs, labels)
              loss.backward()
              optimizer.step()
              
              running_loss += loss.item()
              if i % 100 == 99:
                  print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 100:.3f}')
                  running_loss = 0.0
                  break # Break early for speed in this demo
      print('Finished Training')
  
  if __name__ == '__main__':
      main()
  EOF
  
  python3 train_resnet.py
