apiVersion: v1
kind: Pod
metadata:
  name: amd-gpu-diag
  namespace: default
spec:
  containers:
  - name: diag
    image: rocm/pytorch:latest
    command: ["/bin/bash", "-c", "sleep 3600"]
    resources:
      limits:
        amd.com/gpu: 1
  restartPolicy: Never
